---
title: "20250702_numbat_siCNV_matching_output_plots"
author: "Tatjana Tomek"
format: html
editor: visual
---

## Numbat & inferCNV results matching - output and plots

```{r}
library(qs)
library(Seurat)
library(SeuratObject)
library(tidyverse)
library(GenomicRanges)
library(VennDiagram)
library(gtrellis)
library(circlize)
```

```{r}
# load output files
```

```{r}
shared = read.csv("/g/saka/Tatjana/visium/analysis_1/01_CNV_analysis/siCNV_numbat_matching/LN0438/20250707_new_output/shared_cnvs.csv")
shared$chr <- paste0("chr", shared$chr)
```

```{r}
numbat = read.csv("/g/saka/Tatjana/visium/analysis_1/01_CNV_analysis/siCNV_numbat_matching/LN0438/20250707_new_output/numbat_cnvs.csv")
numbat$CHROM <- paste0("chr", numbat$CHROM)
```

```{r}
sicnv = read.csv("/g/saka/Tatjana/visium/analysis_1/01_CNV_analysis/siCNV_numbat_matching/LN0438/20250707_new_output/sicnv_cnvs.csv")
sicnv = sicnv[,-c(1)]
sicnv$chr <- paste0("chr", sicnv$chr)
```

First, converting our data to genomic ranges objects - this is what gtrellis expects

```{r}
gr_sicnv = GRanges(
  seqnames = sicnv$chr,
  ranges = IRanges(start = sicnv$start, end = sicnv$end),
  cnv_state = sicnv$cnv_state_clean
)

gr_numbat = GRanges(
  seqnames = numbat$CHROM,
  ranges = IRanges(start = numbat$seg_start, end = numbat$seg_end),
  cnv_state = numbat$cnv_state_post
)

gr_shared = GRanges(
  seqnames = shared$chr,
  ranges = IRanges(start = shared$start_match, end = shared$end_match),
  cnv_state = shared$state
)
```

```{r}
#outs_mut <- subset(outs, match == TRUE & nr_match > 0)[ , !(names(outs) %in% "X")]
# so many digits after the comma
#outs_mut$pct_match_siCNV <- round(outs_mut$pct_match_siCNV, 2)
#outs_mut$pct_match_NB <- round(outs_mut$pct_match_NB, 2)
```

Next, make trellis graph of CNVs in numbat, CNVs in siCNV and their overlaps

```{r}
pdf("/g/saka/Tatjana/visium/analysis_1/sicnv_gtrellis_plot.pdf", width = 15, height = 4)

# for some reason, this does not work
col_fun = c("amp" = "red", "del" = "blue")


gtrellis_layout(
  add_name_track = TRUE,
  n_track = 3, 
  equal_width = TRUE,
  title = "CNVs inferred using inferCNV, numbat, and overlapping CNVs", 
  track_ylab = c("inferCNV", "numbat", "overlap"), 
  track_axis = FALSE,
  xlab = "")

add_rect_track(
  gr_sicnv,
  track = 2,
  h1 = 1, 
  h2 = 0,
  gp = gpar(col = NA, fill = col_fun[mcols(gr_sicnv)$cnv_state])
  )
  
add_rect_track(
  gr_numbat,
  track = 3,
  h1 = 1, 
  h2 = 0,
  gp = gpar(col = NA, fill = col_fun[mcols(gr_numbat)$cnv_state])
  )
  
add_rect_track(
  gr_shared,
  track = 4,
  h1 = 1, 
  h2 = 0,
  gp = gpar(col = NA, fill = col_fun[mcols(gr_shared)$cnv_state])
  )


dev.off()

#gtrellis_show_index()

```

```{r}
gtrellis_layout(
  n_track = 1, 
  equal_width = TRUE,
  title = "CNVs inferred using inferCNV",
  track_ylab = c("siCNV"),
  track_axis = FALSE,
  xlab = "")

add_rect_track(
  gr_sicnv,
  h1 = 1, 
  h2 = 0,
  gp = gpar(col = NA, fill = col_fun[mcols(gr_sicnv)$cnv_state])
  )
```

```{r}
library(gtrellis)
library(GenomicRanges)
library(grid)

# 1. Create a color mapping BEFORE plotting
col_fun <- c("amp" = "red", "del" = "blue")

# 2. Convert data.frame to GRanges (gtrellis expects this)


# 3. Start plotting
gtrellis_layout(
  n_track = 1, 
  equal_width = TRUE,
  title = "CNVs inferred using numbat, siCNV, and shared CNVs", 
  track_ylab = "siCNV",
  track_axis = FALSE,
  xlab = ""
)

# 4. Add the rectangles, colored by state
add_rect_track(
  gr,
  h1 = 1, h2 = 0,
  gp = gpar(col = NA, fill = col_fun[mcols(gr)$cnv_state_clean])
)

```

```{r}
bed = generateRandomBed(nr = 100)
```

Now, make Venn diagram

```{r}
# vals
inferCNV <- dim(sicnv)[1]
Numbat <- dim(numbat)[1]
overlap <- dim(outs_mut)[1]

## venn
vennplot <- draw.pairwise.venn(
  area1 = inferCNV,
  area2 = Numbat,
  cross.area = overlap,
  category = c("inferCNV", "Numbat"),
  fill = c("skyblue", "pink"),
  lty = "blank",
  cex = 2,
  cat.cex = 2,
  cat.pos = c(-20, 20),
  cat.dist = 0.05,
  scaled = TRUE
)

```

```{r}
png("/g/saka/Tatjana/visium/analysis_1/01_CNV_analysis/siCNV_numbat_matching/LN0040HD/LN0040HD_venn_plot.png", width = 1200, height = 900, res = 200)

grid.newpage()
grid.draw(vennplot)
grid.text("LN0040HD", y = 0.95, gp = gpar(fontsize = 20, fontface = "bold"))

dev.off()  

```

```{r}
write.table(outs_mut, file="/g/saka/Tatjana/visium/analysis_1/01_CNV_analysis/siCNV_numbat_matching/LN0040HD/LN0040HD_matches.tsv", quote=FALSE, sep="\t", col.names = TRUE, row.names = FALSE)
```
